# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target "Tickts" do

pod 'CocoaLumberjack'
pod 'Parse', '1.4.2'
pod 'ParseFacebookUtils', '1.4.2'

end

target "TicktsTests" do

end

